[project]
name = "learnlangraph1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "langgraph>=1.0.4",
    "notebook>=7.5.0",
    "python-dotenv>=1.2.1",
    "typesense>=1.3.0",
]
